CREATE VIEW VIEW_USER_INFORMATION(USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER, CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTRY, HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY, INSTITUTION_NAME, PROGRAM_YEAR, PROGRAM_CONCENTRATION, PROGRAM_DEGREE)
        AS SELECT  
        FROM USERS;
        


CREATE VIEW VIEW_ARE_FRIENDS(USER1_ID, USER2_ID)
        AS SELECT * FROM FRIENDS;


CREATE VIEW VIEW_PHOTO_INFORMATION(ALBUM_ID, OWNER_ID, COVER_PHOTO_ID, ALBUM_NAME, ALBUM_CREATED_TIME, ALBUM_MODIFIED_TIME, ALBUM_LINK, ALBUM_VISIBILITY, PHOTO_ID, PHOTO_CAPTION, PHOTO_CREATED_TIME, PHOTO_MODIFIED_TIME, PHOTO_LINK)
        AS SELECT 
        FROM PHOTOS;





CREATE VIEW VIEW_EVENT_INFORMATION(EVENT_ID, EVENT_CREATOR_ID, EVENT_NAME, EVENT_TAGLINE, EVENT_DESCRIPTION, EVENT_HOST, EVENT_TYPE, EVENT_SUBTYPE, EVENT_ADDRESS, EVENT_CITY, EVENT_STATE, EVENT_COUNTRY, EVENT_START_TIME, EVENT_END_TIME)
        AS SELECT U.EVENT_ID, U.EVENT_CREATOR_ID, U.EVENT_NAME, U.EVENT_TAGLINE, U.EVENT_DESCRIPTION, U.EVENT_HOST, U.EVENT_TYPE, U.EVENT_SUBTYPE, U.EVENT_ADDRESS, C.CITY_NAME, C.STATE_NAME, C.COUNTRY_NAME, U.EVENT_START_TIME, U.EVENT_END_TIME
        FROM USER_EVENTS U INNER JOIN CITIES C ON U.EVENT_CITY_ID = C.CITY_ID;



CREATE VIEW VIEW_TAG_INFORMATION(TAG_PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X, TAG_Y)
        AS SELECT TAG_PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X, TAG_Y
        FROM TAGS;
