SELECT DISTINCT S.Subject
FROM SUBJECTS S
WHERE S.SUBJECT NOT IN (SELECT DISTINCT Sub.SUBJECT
                    FROM SUBJECTS Sub, AUTHORS A, BOOKS B
                    WHERE B.SUBJECT_ID = Sub.SUBJECT_ID
                    AND A.AUTHOR_ID = B.AUTHOR_ID)
ORDER BY S.SUBJECT ASC;