SELECT C.CID
FROM Courses C
MINUS
SELECT E.CID
FROM Enrollments E
JOIN Students S ON E.SID = S.SID
WHERE S.Major != 'CS' OR S.Major IS NULL
GROUP BY E.CID
HAVING COUNT(DISTINCT E.SID) >= 10
ORDER BY C.CID DESC;

